language: cpp
sudo: required

env:
  global:



matrix:
  fast_finish: true
  include:
    - os: linux
      dist: bionic
      compiler: 
        - gcc
      addons:
        apt:
          packages:
            - cmake
            - valgrind
      env:
        - GCC_MEMCHECK=true
    - os: linux
      dist: bionic
      compiler: gcc
      env:
       - COVERAGE=true

before_install:
- pyenv versions
- pyenv global 3.8

install:
- pip install conan
- conan user
- conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

script:
  sh ./travis_script.sh

after_success:
- echo == Build success ==
- bash <(curl -s https://codecov.io/bash)

after_failure:
- echo == Build failed ==
