language: cpp
sudo: required

env:
  global:



matrix:
  fast_finish: true
  include:
    - os: linux
      dist: bionic
      compiler: 
        - gcc
      addons:
        apt:
          packages:
            - cmake
            - valgrind
    - os: linux
      compiler: clang-7.0




before_install:
- pyenv versions
- pyenv global 3.8

install:
- pip install conan
- conan user

script:
- mkdir -p build
- cd build
- conan install -s compiler.libcxx=libstdc++11 ..
- cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON .. 
- make  - 
- make test
- ctest --overwrite MemoryCheckCommandOptions="--leak-check=full --error-exitcode=100" -T memcheck

after_success:
- echo == Build success ==

after_failure:
- echo == Build failed ==