language: cpp
sudo: required

env:
  global:



matrix:
  fast_finish: true
  include:
    - os: linux
      dist: bionic
      compiler: 
        - gcc
      addons:
        apt:
          packages:
            - cmake
            - valgrind
      env:
        - GCC_MEMCHECK=true
#    - os: linux
#      dist: bionic
#      compiler: clang-7.0
#      env:
#        - USE_CLANG=true




before_install:
- pyenv versions
- pyenv global 3.8

install:
- pip install conan
- conan user

script:
  sh ./travis_script.sh

after_success:
- echo == Build success ==

after_failure:
- echo == Build failed ==