language: cpp
sudo: required

env:
  global:



matrix:
  fast_finish: true
  include:
#
# gcc-4.8 (trusty) full host and cross build with tests:
# doc, cert, cross-mingw32, cross-mingw64, cross-linux32, cross-raspi, linux64,
    - os: linux
      dist: bionic
      compiler: gcc
      addons:
        apt:
          packages:
            - cmake
            # tests
            # - python3
            - valgrind
      env:
        - DEBIAN=true



before_install:
- pyenv versions
#- pyenv install 3.6.0
- pyenv global 3.8

install:
- pip install conan
- conan user
- conan profile update settings.compiler.libcxx=libstdc++11 default

script:
- mkdir -p build
- cd build
- conan install ..
- cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON .. 
- make  - 
- make test
- 

after_success:
- echo == Build success ==

after_failure:
- echo == Build failed ==