language: c
sudo: required

env:
  global:



matrix:
  fast_finish: true
  include:
#
# gcc-4.8 (trusty) full host and cross build with tests:
# doc, cert, cross-mingw32, cross-mingw64, cross-linux32, cross-raspi, linux64,
    - os: linux
      dist: xenial
      compiler: gcc
      addons:
        apt:
          packages:
            - cmake
            # tests
            - pyenv
            - python3
            - valgrind
      env:
        - DEBIAN=true



before_install:
- pyenv install 3.5.0
- pyenv global 3.5.0

install:
- pip install conan
- conan user

script:
- mkdir -p build
- cd build
- conan install ..
- cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON .. 
- make  - 

after_success:
- echo == Build success ==

after_failure:
- echo == Build failed ==